/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7984Receiver,
  IERC7984ReceiverInterface,
} from "../../../../../@openzeppelin/contracts-confidential/contracts/interfaces/IERC7984Receiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "amount",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onConfidentialTransferReceived",
    outputs: [
      {
        internalType: "ebool",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC7984Receiver__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7984ReceiverInterface {
    return new Interface(_abi) as IERC7984ReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7984Receiver {
    return new Contract(address, _abi, runner) as unknown as IERC7984Receiver;
  }
}
