/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VeilWhitelistInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addWhitelist"
      | "campaignCount"
      | "campaigns"
      | "checkAccessAll"
      | "checkAccessRange"
      | "clearWhitelist"
      | "confidentialProtocolId"
      | "createCampaign"
      | "getCampaignInfo"
      | "getEncryptedWhitelistAt"
      | "getMyLastCheck"
      | "isCampaignOwner"
      | "removeWhitelistAt"
      | "removeWhitelistBatch"
      | "transferCampaignOwnership"
      | "wlSize"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "CampaignOwnershipTransferred"
      | "WhitelistAdded"
      | "WhitelistCleared"
      | "WhitelistRemoved"
  ): EventFragment;

  encodeFunctionData(functionFragment: "addWhitelist", values: [BigNumberish, BytesLike[], BytesLike]): string;
  encodeFunctionData(functionFragment: "campaignCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "campaigns", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "checkAccessAll", values: [BigNumberish, BytesLike, BytesLike]): string;
  encodeFunctionData(
    functionFragment: "checkAccessRange",
    values: [BigNumberish, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "clearWhitelist", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "confidentialProtocolId", values?: undefined): string;
  encodeFunctionData(functionFragment: "createCampaign", values: [string]): string;
  encodeFunctionData(functionFragment: "getCampaignInfo", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "getEncryptedWhitelistAt", values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: "getMyLastCheck", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "isCampaignOwner", values: [BigNumberish, AddressLike]): string;
  encodeFunctionData(functionFragment: "removeWhitelistAt", values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: "removeWhitelistBatch", values: [BigNumberish, BigNumberish[]]): string;
  encodeFunctionData(functionFragment: "transferCampaignOwnership", values: [BigNumberish, AddressLike]): string;
  encodeFunctionData(functionFragment: "wlSize", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "addWhitelist", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "campaignCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkAccessAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkAccessRange", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clearWhitelist", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "confidentialProtocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createCampaign", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCampaignInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEncryptedWhitelistAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMyLastCheck", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCampaignOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeWhitelistAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeWhitelistBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transferCampaignOwnership", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wlSize", data: BytesLike): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [campaignId: BigNumberish, owner: AddressLike, name: string];
  export type OutputTuple = [campaignId: bigint, owner: string, name: string];
  export interface OutputObject {
    campaignId: bigint;
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignOwnershipTransferredEvent {
  export type InputTuple = [campaignId: BigNumberish, prevOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [campaignId: bigint, prevOwner: string, newOwner: string];
  export interface OutputObject {
    campaignId: bigint;
    prevOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistAddedEvent {
  export type InputTuple = [campaignId: BigNumberish, count: BigNumberish];
  export type OutputTuple = [campaignId: bigint, count: bigint];
  export interface OutputObject {
    campaignId: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistClearedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistRemovedEvent {
  export type InputTuple = [campaignId: BigNumberish, index: BigNumberish];
  export type OutputTuple = [campaignId: bigint, index: bigint];
  export interface OutputObject {
    campaignId: bigint;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VeilWhitelist extends BaseContract {
  connect(runner?: ContractRunner | null): VeilWhitelist;
  waitForDeployment(): Promise<this>;

  interface: VeilWhitelistInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  addWhitelist: TypedContractMethod<
    [campaignId: BigNumberish, addrsCt: BytesLike[], attestation: BytesLike],
    [void],
    "nonpayable"
  >;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, string] & {
        owner: string;
        exists: boolean;
        name: string;
      },
    ],
    "view"
  >;

  checkAccessAll: TypedContractMethod<
    [campaignId: BigNumberish, userAddrCt: BytesLike, attestation: BytesLike],
    [string],
    "nonpayable"
  >;

  checkAccessRange: TypedContractMethod<
    [campaignId: BigNumberish, userAddrCt: BytesLike, attestation: BytesLike, start: BigNumberish, end: BigNumberish],
    [string],
    "nonpayable"
  >;

  clearWhitelist: TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createCampaign: TypedContractMethod<[name: string], [bigint], "nonpayable">;

  getCampaignInfo: TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [string, boolean, string, bigint] & {
        owner: string;
        exists: boolean;
        name: string;
        whitelistSize: bigint;
      },
    ],
    "view"
  >;

  getEncryptedWhitelistAt: TypedContractMethod<[campaignId: BigNumberish, i: BigNumberish], [string], "view">;

  getMyLastCheck: TypedContractMethod<[campaignId: BigNumberish], [string], "view">;

  isCampaignOwner: TypedContractMethod<[campaignId: BigNumberish, account: AddressLike], [boolean], "view">;

  removeWhitelistAt: TypedContractMethod<[campaignId: BigNumberish, index: BigNumberish], [void], "nonpayable">;

  removeWhitelistBatch: TypedContractMethod<[campaignId: BigNumberish, indices: BigNumberish[]], [void], "nonpayable">;

  transferCampaignOwnership: TypedContractMethod<
    [campaignId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  wlSize: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: "addWhitelist"
  ): TypedContractMethod<
    [campaignId: BigNumberish, addrsCt: BytesLike[], attestation: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "campaignCount"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "campaigns"): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, string] & {
        owner: string;
        exists: boolean;
        name: string;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkAccessAll"
  ): TypedContractMethod<
    [campaignId: BigNumberish, userAddrCt: BytesLike, attestation: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkAccessRange"
  ): TypedContractMethod<
    [campaignId: BigNumberish, userAddrCt: BytesLike, attestation: BytesLike, start: BigNumberish, end: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(nameOrSignature: "clearWhitelist"): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "confidentialProtocolId"): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "createCampaign"): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(nameOrSignature: "getCampaignInfo"): TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [string, boolean, string, bigint] & {
        owner: string;
        exists: boolean;
        name: string;
        whitelistSize: bigint;
      },
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedWhitelistAt"
  ): TypedContractMethod<[campaignId: BigNumberish, i: BigNumberish], [string], "view">;
  getFunction(nameOrSignature: "getMyLastCheck"): TypedContractMethod<[campaignId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isCampaignOwner"
  ): TypedContractMethod<[campaignId: BigNumberish, account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeWhitelistAt"
  ): TypedContractMethod<[campaignId: BigNumberish, index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeWhitelistBatch"
  ): TypedContractMethod<[campaignId: BigNumberish, indices: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferCampaignOwnership"
  ): TypedContractMethod<[campaignId: BigNumberish, newOwner: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "wlSize"): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignOwnershipTransferred"
  ): TypedContractEvent<
    CampaignOwnershipTransferredEvent.InputTuple,
    CampaignOwnershipTransferredEvent.OutputTuple,
    CampaignOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistAdded"
  ): TypedContractEvent<
    WhitelistAddedEvent.InputTuple,
    WhitelistAddedEvent.OutputTuple,
    WhitelistAddedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistCleared"
  ): TypedContractEvent<
    WhitelistClearedEvent.InputTuple,
    WhitelistClearedEvent.OutputTuple,
    WhitelistClearedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistRemoved"
  ): TypedContractEvent<
    WhitelistRemovedEvent.InputTuple,
    WhitelistRemovedEvent.OutputTuple,
    WhitelistRemovedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,address,string)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignOwnershipTransferred(uint256,address,address)": TypedContractEvent<
      CampaignOwnershipTransferredEvent.InputTuple,
      CampaignOwnershipTransferredEvent.OutputTuple,
      CampaignOwnershipTransferredEvent.OutputObject
    >;
    CampaignOwnershipTransferred: TypedContractEvent<
      CampaignOwnershipTransferredEvent.InputTuple,
      CampaignOwnershipTransferredEvent.OutputTuple,
      CampaignOwnershipTransferredEvent.OutputObject
    >;

    "WhitelistAdded(uint256,uint256)": TypedContractEvent<
      WhitelistAddedEvent.InputTuple,
      WhitelistAddedEvent.OutputTuple,
      WhitelistAddedEvent.OutputObject
    >;
    WhitelistAdded: TypedContractEvent<
      WhitelistAddedEvent.InputTuple,
      WhitelistAddedEvent.OutputTuple,
      WhitelistAddedEvent.OutputObject
    >;

    "WhitelistCleared(uint256)": TypedContractEvent<
      WhitelistClearedEvent.InputTuple,
      WhitelistClearedEvent.OutputTuple,
      WhitelistClearedEvent.OutputObject
    >;
    WhitelistCleared: TypedContractEvent<
      WhitelistClearedEvent.InputTuple,
      WhitelistClearedEvent.OutputTuple,
      WhitelistClearedEvent.OutputObject
    >;

    "WhitelistRemoved(uint256,uint256)": TypedContractEvent<
      WhitelistRemovedEvent.InputTuple,
      WhitelistRemovedEvent.OutputTuple,
      WhitelistRemovedEvent.OutputObject
    >;
    WhitelistRemoved: TypedContractEvent<
      WhitelistRemovedEvent.InputTuple,
      WhitelistRemovedEvent.OutputTuple,
      WhitelistRemovedEvent.OutputObject
    >;
  };
}
