/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConfidentialFungibleTokenERC20Wrapper__factory } from "./ConfidentialFungibleTokenERC20Wrapper__factory";
