/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  EthereumConfig,
  EthereumConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/EthereumConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x608060405234610125576000606061001561012a565b82815282602082015282604082015201526000606061003261012a565b8281526020810183905260408082018490529101919091527fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea60080546001600160a01b03199081169091557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6018054821690557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6028054821690557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6038054821690557f5ea69329017273582817d320489fbd94f775580e90c092699ca6f3d12fdf7d008054909116905551601190816101608239f35b600080fd5b60405190608082016001600160401b0381118382101761014957604052565b634e487b7160e01b600052604160045260246000fdfe600080fdfea164736f6c634300081a000a";

type EthereumConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumConfig__factory extends ContractFactory {
  constructor(...args: EthereumConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthereumConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EthereumConfig__factory {
    return super.connect(runner) as EthereumConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumConfigInterface {
    return new Interface(_abi) as EthereumConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthereumConfig {
    return new Contract(address, _abi, runner) as unknown as EthereumConfig;
  }
}
