/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  SepoliaConfig,
  SepoliaConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/SepoliaConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x6080604052346101af57600060606100156101b4565b828152826020820152826040820152015273901f8942346f7ab3a01f6d7613119bca447bb03060606100456101b4565b7350157cffd6bbfa2dece204a89ec419c23ef5755d80825273cd3ab3bd6bcc0c0bf3e27912a92043e817b1cf6960208301819052731364cbbf2cdf5032c47d8226a6f6fbd2afcdacac604080850182905294909301949094527fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea60080546001600160a01b031990811690921790557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea601805482169094179093557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6028054841690911790557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6038054831673901f8942346f7ab3a01f6d7613119bca447bb0301790557f5ea69329017273582817d320489fbd94f775580e90c092699ca6f3d12fdf7d00805490921673a02cda4ca3a71d7c46997716f4283aa851c288121790915551601190816101ea8239f35b600080fd5b60405190608082016001600160401b038111838210176101d357604052565b634e487b7160e01b600052604160045260246000fdfe600080fdfea164736f6c634300081a000a";

type SepoliaConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SepoliaConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SepoliaConfig__factory extends ContractFactory {
  constructor(...args: SepoliaConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SepoliaConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SepoliaConfig__factory {
    return super.connect(runner) as SepoliaConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SepoliaConfigInterface {
    return new Interface(_abi) as SepoliaConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SepoliaConfig {
    return new Contract(address, _abi, runner) as unknown as SepoliaConfig;
  }
}
